islandora_openseadragon.settings:
  type: config_object
  label: Settings
  mapping:
    islandora_openseadragon_settings:
      type: islandora_openseadragon_js_config
    islandora_openseadragon_tile_size:
      type: integer
    islandora_openseadragon_tile_overlap:
      type: integer
    islandora_openseadragon_fit_to_aspect_ratio:
      type: boolean
    islandora_openseadragon_tilesource:
      type: string
